# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c9d293b09db24a11db63a81f3be8e053d8b127bac233b3343889ef76800a8702a96603755462be990d1cd0d36da004527c91cd8d4429defd6e65971937a679

test:
  secret_key_base: dbed60dc6aaf600f2b5c009177b15b993b423a9dfc5ef9fb6905de7a42f6b1d63539b6020b128119340275d20a3f67907c56344334faf92889fca8097d52af6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
